// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiMySQL.Data;

#nullable disable

namespace WebApiMySQL.Migrations
{
    [DbContext(typeof(WebApiMySQLContext))]
    partial class WebApiMySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("WebApiMySQL.Models.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("friend_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePhone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("home_phone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("post_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("friend", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Thimi",
                            City = "huusdfb",
                            FirstName = "sdfasw",
                            HomePhone = "12345678",
                            LastName = "terei",
                            PostCode = "12345",
                            State = "3"
                        });
                });

            modelBuilder.Entity("WebApiMySQL.Models.VideoCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("video_collection_id");

                    b.Property<int>("FriendId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("friend_id");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("movie_title");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearReleased")
                        .IsRequired()
                        .HasColumnType("INTEGER")
                        .HasColumnName("year_released");

                    b.HasKey("Id");

                    b.HasIndex("FriendId");

                    b.ToTable("video_collection", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FriendId = 1,
                            Length = 2.5,
                            MovieTitle = "This is bull",
                            Rating = 4.5,
                            Subject = "",
                            YearReleased = 2020
                        });
                });

            modelBuilder.Entity("WebApiMySQL.Models.VideoCollection", b =>
                {
                    b.HasOne("WebApiMySQL.Models.Friend", "Friend")
                        .WithMany("videoCollections")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Friend");
                });

            modelBuilder.Entity("WebApiMySQL.Models.Friend", b =>
                {
                    b.Navigation("videoCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
